@tool
extends EditorPlugin

func _enter_tree() -> void:
	add_tool_menu_item("Generate Input Actions", Callable(self, "_run"))
	pass


func _exit_tree() -> void:
	remove_tool_menu_item("Generate Input Actions")
	pass


func _run():
	var path = "res://Scripts/InputActions.cs"
	var file = FileAccess.open(path, FileAccess.WRITE)
	if not file:
		push_error("Could not open file: %s" % path)
		return
	
	file.store_line("// Auto-generated by input_actions_generator.gd")
	file.store_line("public static class InputActions")
	file.store_line("{")
	
	# Read from project.godot
	var config = ConfigFile.new()
	var err = config.load("res://project.godot")
	if err != OK:
		push_error("Failed to load project.godot")
		return
	
	if config.has_section("input"):
		var actions = config.get_section_keys("input")
		for name in actions:
			var const_name = name.replace(" ", "_")
			file.store_line("    public const string " + const_name + " = \"" + name + "\";")
	else:
		push_warning("No [input] section found in project.godot")

	file.store_line("}")
	file.close()
	print("Generated InputActions.cs successfully.")
