@tool
extends EditorPlugin

const key = "input_action_generator/output_path"

func _enter_tree() -> void:
	var settings = EditorInterface.get_editor_settings()
	if not settings.has_setting(key):
		settings.set_setting(key, "res://")
		settings.add_property_info({
			"name": key,
			"type": TYPE_STRING,
			"hint": PROPERTY_HINT_DIR,
		})
		settings.save()
	
	add_tool_menu_item("Generate Input Actions", Callable(self, "_run"))
	pass


func _exit_tree() -> void:
	remove_tool_menu_item("Generate Input Actions")
	pass


func _run():
	var settings = EditorInterface.get_editor_settings()
	var path = settings.get_setting(key)
		
	if not path.get_extension().is_empty():
		path = path.get_base_dir()
		
	if not DirAccess.dir_exists_absolute(path):
		DirAccess.make_dir_recursive_absolute(path)
	
	path = path.path_join("InputActions.cs");
	
	var file = FileAccess.open(path, FileAccess.WRITE)
		
	if not file:
		push_error("Could not open file: %s" % path)
		return
	
	file.store_line("// Auto-generated by input_actions_generator.gd")
	file.store_line("public static class InputActions")
	file.store_line("{")
	
	var config = ConfigFile.new()
	var err = config.load("res://project.godot")
	if err != OK:
		push_error("Failed to load project.godot")
		return
	
	if config.has_section("input"):
		var actions = config.get_section_keys("input")
		for name in actions:
			var const_name = name.replace(" ", "_")
			file.store_line("    public const string " + const_name + " = \"" + name + "\";")
	else:
		push_warning("No [input] section found in project.godot")

	file.store_line("}")
	file.close()
	print("Generated InputActions.cs successfully.")
	
	var fs = EditorInterface.get_resource_filesystem();
	fs.scan()
